// <auto-generated />
namespace OMinD.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserFullName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserFullName));
        
        string IMigrationMetadata.Id
        {
            get { return "201806130859366_UserFullName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
